name: CI

on:
  push:
    branches: [ staging ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        working-directory: ./src
      - run: npm test
        working-directory: ./src
      - run: npx eslint .
        working-directory: ./src

      # Build artifact step
      - run: npm run build
        working-directory: ./src

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: src/build/
